name: VRT

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: vrt-${{ github.ref }}
  cancel-in-progress: true

jobs:
  compare:
    uses: ./.github/workflows/vrt-run.yml
    with:
      update-snapshots: false
